[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
meteora_cpi = "GUESbdzbRfwNuajJn27WpAiMoG8qif8rtLP13Pjy3Cza"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "../key/uu.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
